#!/bin/sh

TERMINFO=~/.terminfo
rm -rf "$TERMINFO"

tmp=$(mktemp)

cat > "$tmp" <<EOF
tmux|tmux terminal multiplexer,
	ritm=\E[23m, rmso=\E[27m, sitm=\E[3m, smso=\E[7m, Ms@,
	use=xterm+tmux, use=screen,

tmux-256color|tmux with 256 colors and italic,
	use=xterm+256setaf, use=tmux,
EOF

tic -x "$tmp"
